const directExpressHeaders = Object.freeze({
  DATE: 1,
  "TRANSACTION ID": 2,
  DESCRIPTION: 3,
  AMOUNT: 4,
  "TRANSACTION TYPE": 5,
  CITY: 6,
  STATE: 7,
  COUNTRY: 8,
  1: "DATE",
  2: "TRANSACTION ID",
  3: "DESCRIPTION",
  4: "AMOUNT",
  5: "TRANSACTION TYPE",
  6: "CITY",
  7: "STATE",
  8: "COUNTRY",
});

const transactionHeaders = Object.freeze({
  0: "",
  1: "Date",
  2: "Description",
  3: "Category",
  4: "Amount",
  5: "Account",
  6: "Account #",
  7: "Institution",
  8: "Month",
  9: "Week",
  10: "Transaction ID",
  11: "Account ID",
  12: "Check Number",
  13: "Full Description",
  14: "Date Added",
  15: "Categorized Date",
  "": 0,
  Date: 1,
  Description: 2,
  Category: 3,
  Amount: 4,
  Account: 5,
  "Account #": 6,
  Institution: 7,
  Month: 8,
  Week: 9,
  "Transaction ID": 10,
  "Account ID": 11,
  "Check Number": 12,
  "Full Description": 13,
  "Date Added": 14,
  "Categorized Date": 15,
});
